spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/education_system_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/education_system_db
#spring.datasource.username=root
#spring.datasource.password=
#
#spring.jpa.show-sql=true

